DROP TABLE IF EXISTS PROGRAMS;
DROP TABLE IF EXISTS CHANNEL_PACKAGES;
DROP TABLE IF EXISTS CHANNELS;

CREATE TABLE IF NOT EXISTS CHANNELS (
  ID SERIAL PRIMARY KEY ,
  CHANNEL_ID VARCHAR(255) NOT NULL UNIQUE,
  DISPLAY_NAME VARCHAR(255) NOT NULL,
  ICON TEXT DEFAULT NULL,
  CONSTRAINT unique_channel_id UNIQUE (CHANNEL_ID)
);

CREATE TABLE IF NOT EXISTS PROGRAMS (
  ID SERIAL PRIMARY KEY,
  CHANNEL_ID VARCHAR(255) NOT NULL,
  START_TIME TIMESTAMP NOT NULL,
  END_TIME TIMESTAMP NOT NULL,
  TITLE TEXT NOT NULL,
  SUBTITLE TEXT DEFAULT NULL,
  DESCRIPTION TEXT DEFAULT NULL,
  CATEGORIES VARCHAR(255) DEFAULT NULL,
  ICON TEXT DEFAULT NULL,
  EPISODE_NUM VARCHAR(50) DEFAULT NULL,
  RATING_SYSTEM VARCHAR(50) DEFAULT NULL,
  RATING_VALUE VARCHAR(50) DEFAULT NULL,
  RATING_ICON TEXT DEFAULT NULL,
  FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(CHANNEL_ID)
);

CREATE TABLE IF NOT EXISTS CHANNEL_PACKAGES (
  ID SERIAL PRIMARY KEY,
  CHANNEL_ID VARCHAR(255) NOT NULL,
  PACKAGE_ID VARCHAR(255) NOT NULL,
  FOREIGN KEY (CHANNEL_ID) REFERENCES CHANNELS(CHANNEL_ID)
);